services:
  - type: web
    name: cv
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: HOSTNAME
        value: 0.0.0.0
